### PR TITLE
Migration from Groovy to Kotlin DSL

### PR DESCRIPTION
**Pull request by utkarsh006**
- Fixes Issue #1 
- The App build is successfully generated.
- [Resource for this PR](https://developer.android.com/build/migrate-to-kotlin-dsl)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@bhoomi0104 Kindly Review.

**Comment by bhoomigadhiya** [comment]
Please make your PR on the develop branch rather than the master.

**Comment by bhoomigadhiya** [comment]
Read it here: https://github.com/bhoomi0104/XML-To-Compose/blob/master/CONTRIBUTING.md

**Comment by utkarsh006** [comment]
@bhoomi0104 Make develop as the default branch of this repo.

**Comment by bhoomigadhiya** [comment]
You can change the pull request branch this way 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by utkarsh006** [comment]
@bhoomi0104 Yes thanks, but above move would definitely help the future contributors.

**Comment by bhoomigadhiya** [comment]
Yes sure thanks

**Pull request closed without merging**
